services:
  - type: web
    name: hormozgan-driver-pro121
    env: node
    buildCommand: |
      pnpm install
      pnpm -r run build
    startCommand: |
      cd apps/driver-service && pnpm start
    envVars:
      - key: NODE_ENV
        value: production
    branches:
      - main
